# Generated by Django 5.2 on 2025-05-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('category', models.CharField(choices=[('full_stack', 'Full Stack Development'), ('mobile_app', 'Mobile App Development'), ('data_science', 'Data Science'), ('data_analytics', 'Data Analytics'), ('software_testing', 'Software Testing'), ('digital_marketing', 'Digital Marketing'), ('ux_ui', 'UX/UI Design'), ('cyber_security', 'Cyber Security')], max_length=50)),
                ('subcategory', models.CharField(blank=True, choices=[('mern_stack', 'MERN Stack'), ('python_stack', 'Python Stack'), ('java_stack', 'Java Stack'), ('dotnet_stack', 'DotNet Stack'), ('android', 'Android'), ('ios', 'iOS'), ('flutter_app', 'Flutter App'), ('flutter_app_development', 'Flutter App Development'), ('data_science_training', 'Data Science Training'), ('machine_learning_training', 'Machine Learning Training'), ('data_analytics_training', 'Data Analytics Training'), ('business_analytics_training', 'Business Analytics Training'), ('software_testing_training', 'Software Testing Training'), ('selenium_automation_training', 'Selenium Automation Training'), ('manual_testing_training', 'Manual Testing Training'), ('digital_marketing_training', 'Digital Marketing Training'), ('ux_ui_training', 'UX-UI Training'), ('ethical_hacking_training', 'Ethical Hacking Training')], max_length=50, null=True)),
                ('learning_outcomes', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instructor_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('students_enrolled', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=50)),
                ('certification', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('promo_video', models.FileField(blank=True, null=True, upload_to='course_videos/')),
                ('technologies_covered', models.TextField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.PositiveIntegerField()),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
