# Generated by Django 5.2 on 2025-05-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_pilot_app', '0004_cart_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='checked_out_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='total_price',
            new_name='price',
        ),
    ]
