# Generated by Django 5.2 on 2025-06-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_pilot_app', '0007_course_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomCourse',
        ),
    ]
