# Generated by Django 5.2 on 2025-06-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_pilot_app', '0008_delete_customcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/'),
        ),
    ]
