# Generated by Django 5.2 on 2025-06-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_pilot_app', '0010_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
