# Generated by Django 5.2 on 2025-06-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_pilot_app', '0012_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Card')], default='upi', max_length=10),
        ),
    ]
