# Generated by Django 5.2 on 2025-06-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_pilot_app', '0013_checkout_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('paytm', 'Paytm'), ('phonepe', 'PhonePe'), ('card', 'Credit/Debit Card')], default='upi', max_length=10),
        ),
    ]
